name: Releases workflow

on:
  push:
    tags:
      - "**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  FOUNDRY_PROFILE: ci

jobs:
  upload-release-artifacts:
    name: Upload release artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Create artifacts
        run: npm run compile
      - name: Push release to S3
        run: npm run hardhat soko push -- --artifact-path ./artifacts --tag assured-counter:${{ github.ref_name }}
